In [1]:
# Start ---->   23 Feb 2024 ,thursday 

In [2]:
# 1. CMD
# 2. jupyter notebook > this service/ widow should always be running
# 3. default location > http://localhost:8888/tree
# 4. / means C:\ is root Folder
# 5. Create a new Python file

#  Intro to Numpy


In [3]:
# https://numpy.org/doc/stable/user/quickstart.html#an-example

In [4]:
a1 = [1,2,3,4,5,6,7,8]
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8]


In [5]:
a2 = [11,12,13,14,15,16]
print(a2)

[11, 12, 13, 14, 15, 16]


In [6]:
# make elements doubles in list
a1 = [1,2,3,4,5,6,7,8]
print(a1 *2)

[1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8]


In [8]:
# need to be apply loop

for i in a1:
    print(i*2)

2
4
6
8
10
12
14
16


In [9]:
for i in a2:
    print(i*2)

22
24
26
28
30
32


In [11]:
# also use list comprehension to achive this task in one line :

aa = [i*2 for i in a1]
print(aa)

[2, 4, 6, 8, 10, 12, 14, 16]


In [12]:
bb = [i*2 for i in a2]
print(bb)

[22, 24, 26, 28, 30, 32]


In [18]:
# Q:make Sqare of this elements

print(a1)
for i in a1:
    print(i**2)
    

[1, 2, 3, 4, 5, 6, 7, 8]
1
4
9
16
25
36
49
64


In [19]:
for i in a2:
    print(i**2)

121
144
169
196
225
256


# better approach ???

In [20]:
import numpy as np

In [21]:
print('Hello World')

Hello World


In [22]:
print('Welcome to in DataScience Program')

Welcome to in DataScience Program


In [24]:
name = "Arjun Jadhav"
print(name.casefold()) # to convert small case

arjun jadhav


In [25]:
a1 = [1,2,3,4,5,6,7,8,9,10]
arr1 = np.array(a1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
print(arr1 * 2)

[ 2  4  6  8 10 12 14 16 18 20]


In [27]:
print(arr1*2)  #numpy supports elemntwise operation 

[ 2  4  6  8 10 12 14 16 18 20]


In [28]:
print(arr1 ** 2)

[  1   4   9  16  25  36  49  64  81 100]


In [29]:
print(arr1 ** 5)

[     1     32    243   1024   3125   7776  16807  32768  59049 100000]
