In [1]:
import numpy as np

In [5]:
#what is numpy attributes ?
#1.NumPy attributes are properties or characteristics associated with NumPy arrays. 
#2.These attributes provide important information about the array's shape, size, data type, 
#       memory layout, and other relevant metadata.
#3.Understanding and utilizing NumPy attributes is crucial for efficient array manipulation, 
#                           data analysis, and numerical computation tasks.



#Some commonly used NumPy attributes include:-

# shape: This attribute returns a tuple indicating the size of each dimension of the array. For example, for a 2D array, shape will be (rows, columns).

# dtype: The dtype attribute specifies the data type of the elements stored in the array, such as integer, float, etc.

# size: The size attribute represents the total number of elements in the array.

# ndim: This attribute returns the number of dimensions (axes) of the array.

# itemsize: The itemsize attribute specifies the size in bytes of each element in the array.

# nbytes: This attribute returns the total number of bytes consumed by the elements of the array.

# strides: The strides attribute indicates the number of bytes to step in each dimension when traversing the array.

# flags: The flags attribute provides information about memory layout, such as whether the array is contiguous or not.

# data: The data attribute is a buffer object pointing to the start of the array's data.

In [4]:
# significance of numpy attributes:

# These attributes play a significant role in various aspects of array manipulation and computation. For example:

# Shape and Size: They help in understanding the array's dimensions and the total number of elements,
#                  which is essential for reshaping, indexing, and slicing arrays.

# Data Type: It ensures that operations are performed with appropriate data types,
#             preventing errors and optimizing memory usage.

# Memory Layout: Information about strides and memory layout aids in optimizing performance, 
#               especially when dealing with large arrays and memory efficiency.

# Buffer Handling: The data attribute provides direct access to the underlying memory buffer, facilitating interoperability with other 
#     libraries and efficient data processing.

In [7]:
a1 = [11,22,33,44,55]
print(a1)
print(type(a1))

[11, 22, 33, 44, 55]
<class 'list'>


In [15]:
arr1 = np.array(a1) # Converting list into array.
print(arr1)
print(type(arr1))

[11 22 33 44 55]
<class 'numpy.ndarray'>


# what is difference between Array Vs list

In [ ]:
# Certainly! Here's a concise differentiation between arrays and lists in Python presented in a column format:

# | Attribute       | Array                        | List                         |
# |-----------------|------------------------------|------------------------------|
# | **Data Structure** | Homogeneous (elements are of the same type) | Heterogeneous (elements can be of different types) |
# | **Mutable**       | Yes                          | Yes                          |
# | **Length**        | Fixed (after initialization) | Variable                     |
# | **Performance**   | Faster (optimized for numerical operations) | Slower (optimized for flexibility) |
# | **Functions**     | NumPy library provides extensive functions for array manipulation | Limited built-in functions for lists |
# | **Syntax**        | Uses array creation functions from NumPy library | Uses square brackets `[ ]` for creation and manipulation |
# | **Memory Usage**  | More memory-efficient due to contiguous storage | Less memory-efficient due to dynamic storage allocation |

# This comparison highlights some key differences between arrays and lists in Python, including their data structure, mutability, length, performance, available functions, syntax, and memory usage.

In [16]:
a2 = [1,2,3,4,5,6]
print(type(a2))

<class 'list'>


In [17]:
arr2 = np.array(a2) #converting list into array
print(type(arr2))


<class 'numpy.ndarray'>


#typecasting Example from Python basics
number =1000
yy = str(number) # number is converted into the string
print(yy)
print(type(yy))


In [21]:
numA = 2300
print(type(str(numA)))

<class 'str'>


# ElementWise Operation

In [22]:
s1 = [100,200,300,400,500]
for i in s1:
    print(i*2)

200
400
600
800
1000


In [24]:
for i in s1:
    print(i** 2)

10000
40000
90000
160000
250000


In [25]:
for i in s1:
    print(i**3)

1000000
8000000
27000000
64000000
125000000


In [26]:
# list comprehension

aa = [i ** 2 for i in s1]
print(aa)

[10000, 40000, 90000, 160000, 250000]


In [27]:
bb = [i**3 for i in s1]
print(bb)

[1000000, 8000000, 27000000, 64000000, 125000000]


In [28]:
print(cc = [i**3 for i in s1])


TypeError: 'cc' is an invalid keyword argument for print()

In [29]:
cc = [i**5 for i in s1]
print(cc)

[10000000000, 320000000000, 2430000000000, 10240000000000, 31250000000000]


In [30]:
arr1

array([11, 22, 33, 44, 55])

In [31]:
arr1 * 2

array([ 22,  44,  66,  88, 110])

In [32]:
arr1 **2

array([ 121,  484, 1089, 1936, 3025])

In [33]:
arr1 + arr1

array([ 22,  44,  66,  88, 110])

In [34]:
arr1 * arr1

array([ 121,  484, 1089, 1936, 3025])

In [35]:
arr1 - arr1

array([0, 0, 0, 0, 0])

In [36]:
arr1/arr2

ValueError: operands could not be broadcast together with shapes (5,) (6,) 