In [1]:
import numpy as np

In [2]:
data = np.loadtxt('fitbit.txt',dtype = "str")

In [3]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [4]:
# numpy array is ?
#  a. Homogenous array
#  b . Hetrogenous array


# List is Hetrogenous
# numpy array is Homogenous

In [5]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [6]:
data.ndim

2

In [7]:
data.size

182

In [8]:
data.shape

(26, 7)

In [9]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [10]:
data[4
    ]

array(['10-10-2017', '8538', '300', '307', '5', '0', '68'], dtype='<U10')

In [11]:
data.dtype

dtype('<U10')

In [12]:
type(data)

numpy.ndarray

# Data Cleaning 

In [13]:
# data has no header
# all data is in STRING type

data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [14]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [15]:
data.T[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [16]:
data.T[2]

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [17]:
data.T[9]

IndexError: index 9 is out of bounds for axis 0 with size 7

In [18]:
data.T[6]

array(['68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68'], dtype='<U10')

# Packing of Tuple



In [19]:
tup1 = (11,22,33,44,55,66) #packing of tuple
print(tup1[0])
print(tup1[1])
print(tup1[2])


11
22
33


# Unpacking of tuple

In [20]:
a,b,c,d,e,f=tup1
print(a)
print(b)
print(c)


11
22
33


In [21]:
date ,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg=data.T

In [22]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [23]:
calories_burned

array(['181', '208', '341', '190', '307', '302', '198', '201', '195',
       '327', '331', '318', '344', '204', '180', '201', '329', '315',
       '197', '184', '328', '322', '327', '148', '235', '184'],
      dtype='<U10')

In [24]:
weight_kg

array(['68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68', '68', '68', '68', '68', '68', '68', '68',
       '68', '68', '68', '68'], dtype='<U10')

In [25]:
hours_of_sleep

array(['6', '6', '5', '8', '5', '5', '8', '6', '6', '5', '5', '5', '5',
       '6', '6', '6', '5', '5', '8', '8', '5', '5', '5', '8', '6', '6'],
      dtype='<U10')

In [26]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [27]:
type(step_count)

numpy.ndarray

In [28]:
step_count = np.array(step_count,dtype='int')

In [29]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [30]:
step_count.dtype

dtype('int32')

# DataTypes in Numpy

In [31]:
step_count.dtype

dtype('int32')

In [32]:
type(step_count)

numpy.ndarray

In [33]:
# Changing the 'str' dataType in 'int'

step_count = np.array(step_count,dtype = 'int')

In [34]:
step_count.dtype

dtype('int32')

In [35]:
calories_burned = np.array(calories_burned,dtype = 'int')
hours_of_sleep = np.array(hours_of_sleep,dtype = "int")
weight_kg = np.array(weight_kg,dtype = "int")

In [36]:
calories_burned.dtype

dtype('int32')

In [37]:
hours_of_sleep.dtype

dtype('int32')

In [38]:
weight_kg.dtype

dtype('int32')

In [39]:
calories_burned

array([181, 208, 341, 190, 307, 302, 198, 201, 195, 327, 331, 318, 344,
       204, 180, 201, 329, 315, 197, 184, 328, 322, 327, 148, 235, 184])

In [40]:
hours_of_sleep

array([6, 6, 5, 8, 5, 5, 8, 6, 6, 5, 5, 5, 5, 6, 6, 6, 5, 5, 8, 8, 5, 5,
       5, 8, 6, 6])

In [41]:
weight_kg

array([68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68, 68,
       68, 68, 68, 68, 68, 68, 68, 68, 68])

In [42]:
# focussing on 'mood' data
# data is in numerical form but is repetative
# checking the pattern of data 

In [43]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [44]:
# mood data is categorical

In [45]:
# 100 = sad
# 200 =  neutral
# 300 = happy

In [46]:
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [47]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [48]:
mood == '100' #100 == 'Sad'

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [49]:
mood[mood == '100'] ='Sad'

In [50]:
mood

array(['200', '200', '300', 'Sad', '300', '300', 'Sad', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       'Sad', 'Sad', '300', '300', '300', 'Sad', '200', '200'],
      dtype='<U10')

In [51]:
mood == '200' #200 == 'Neutral'

array([ True,  True, False, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False,  True,  True])

In [52]:
mood[mood == '200'] = 'Neutral'

In [53]:
mood

array(['Neutral', 'Neutral', '300', 'Sad', '300', '300', 'Sad', 'Neutral',
       'Neutral', '300', '300', '300', '300', 'Neutral', 'Neutral',
       'Neutral', '300', '300', 'Sad', 'Sad', '300', '300', '300', 'Sad',
       'Neutral', 'Neutral'], dtype='<U10')

In [54]:
mood[mood == '300'] = 'Happy'

In [55]:
mood

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U10')

In [56]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

# filterning the data

In [65]:
# use the boolean masking for filtering the data.

In [67]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '6', '0', '68'],
       ['07-10-2017', '7167', 'Neutral', '208', '6', '0', '68'],
       ['08-10-2017', '9874', 'Happy', '341', '5', '0', '68'],
       ['09-10-2017', '4969', 'Sad', '190', '8', '0', '68'],
       ['10-10-2017', '8538', 'Happy', '307', '5', '0', '68'],
       ['11-10-2017', '9875', 'Happy', '302', '5', '0', '68'],
       ['12-10-2017', '4662', 'Sad', '198', '8', '0', '68'],
       ['13-10-2017', '6310', 'Neutral', '201', '6', '0', '68'],
       ['14-10-2017', '7556', 'Neutral', '195', '6', '0', '68'],
       ['15-10-2017', '9073', 'Happy', '327', '5', '0', '68'],
       ['16-10-2017', '9690', 'Happy', '331', '5', '0', '68'],
       ['17-10-2017', '9146', 'Happy', '318', '5', '0', '68'],
       ['18-10-2017', '9752', 'Happy', '344', '5', '0', '68'],
       ['19-10-2017', '6974', 'Neutral', '204', '6', '0', '68'],
       ['20-10-2017', '5619', 'Neutral', '180', '6', '0', '68'],
       ['21-10-2017', '6889', 'Neutral', '201',